name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências do Cypress
        working-directory: ./cypress-web-tests
        run: |
          npm ci

      - name: Instalar o Cypress
        working-directory: ./cypress-web-tests
        run: npx cypress install

      - name: Executar testes Cypress
        working-directory: ./cypress-web-tests
        run: npx cypress run --spec "cypress/e2e/login.cy.js"


