name: Pytest - API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        working-directory: ./pytest-api-tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar testes Pytest
        working-directory: ./pytest-api-tests
        run: |
          source venv/bin/activate
          pytest -v
